ContactBundle\Entity\Person:
    type: entity

    associationOverride:
        commWay:
            joinTable:
                name: person_commway
                joinColumns:
                    person_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    commWay_id:
                        referencedColumnName: id

    fields:
        surname:
            type: string
            length: 255

        birthDate:
            type: date

    lifecycleCallbacks: {  }
